from .models import SourceInput


INITIAL_SOURCES = [
    SourceInput(
        slug="alamiria",
        name="الهيئة العامة لشئون المطابع الأميرية",
        url="https://www.alamiria.com",
        source_type="legal",
        ownership_type="government",
    ),
    SourceInput(
        slug="parliament-egypt",
        name="مجلس النواب المصري",
        url="https://www.parliament.gov.eg",
        source_type="official",
        ownership_type="government",
    ),
    SourceInput(
        slug="cabinet-egypt",
        name="مجلس الوزراء المصري",
        url="https://www.cabinet.gov.eg",
        source_type="official",
        ownership_type="government",
    ),
    SourceInput(
        slug="presidency-egypt",
        name="رئاسة جمهورية مصر العربية",
        url="https://www.presidency.eg/ar",
        source_type="official",
        ownership_type="government",
    ),
    SourceInput(
        slug="supreme-constitutional-court",
        name="المحكمة الدستورية العليا",
        url="https://www.sccourt.gov.eg",
        source_type="legal",
        ownership_type="judiciary",
    ),
    SourceInput(
        slug="ministry-of-justice-egypt",
        name="وزارة العدل المصرية",
        url="https://moj.gov.eg",
        source_type="legal",
        ownership_type="government",
    ),
    SourceInput(
        slug="manshurat",
        name="منشورات قانونية",
        url="https://manshurat.org",
        source_type="legal",
        ownership_type="independent_archive",
    ),
    SourceInput(
        slug="capmas",
        name="الجهاز المركزي للتعبئة العامة والإحصاء",
        url="https://www.capmas.gov.eg",
        source_type="statistics",
        ownership_type="government",
    ),
    SourceInput(
        slug="central-bank-egypt",
        name="البنك المركزي المصري",
        url="https://www.cbe.org.eg",
        source_type="statistics",
        ownership_type="government",
    ),
    SourceInput(
        slug="idsc-egypt",
        name="مركز المعلومات ودعم اتخاذ القرار",
        url="https://www.idsc.gov.eg",
        source_type="academic",
        ownership_type="government_research_center",
    ),
    SourceInput(
        slug="eces-egypt",
        name="المركز المصري للدراسات الاقتصادية",
        url="https://eces.org.eg",
        source_type="academic",
        ownership_type="independent_research_center",
    ),
    SourceInput(
        slug="economic-research-forum",
        name="منتدى البحوث الاقتصادية",
        url="https://erf.org.eg",
        source_type="academic",
        ownership_type="regional_research_center",
        language="mixed",
    ),
    SourceInput(
        slug="auc-knowledge-fountain",
        name="AUC Knowledge Fountain",
        url="https://fount.aucegypt.edu",
        source_type="academic",
        ownership_type="university",
        language="en",
    ),
    SourceInput(
        slug="nchr-egypt",
        name="المجلس القومي لحقوق الإنسان",
        url="https://nchr.eg",
        source_type="official",
        ownership_type="national_institution",
    ),
    SourceInput(
        slug="eipr",
        name="المبادرة المصرية للحقوق الشخصية",
        url="https://eipr.org",
        feed_url="https://eipr.org/rss.xml",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="afte",
        name="مؤسسة حرية الفكر والتعبير",
        url="https://afteegypt.org",
        feed_url="https://afteegypt.org/feed",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="ec-rf",
        name="المفوضية المصرية للحقوق والحريات",
        url="https://www.ec-rf.net",
        feed_url="https://www.ec-rf.net/feed/",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="egyptian-front",
        name="الجبهة المصرية لحقوق الإنسان",
        url="https://egyptianfront.org",
        feed_url="https://egyptianfront.org/feed/",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="committee-for-justice",
        name="Committee for Justice",
        url="https://www.cfjustice.org",
        feed_url="https://www.cfjustice.org/feed/",
        source_type="human_rights",
        ownership_type="civil_society",
        language="mixed",
    ),
    SourceInput(
        slug="refugees-platform-egypt",
        name="منصة اللاجئين في مصر",
        url="https://rpegy.org",
        feed_url="https://rpegy.org/feed/",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="cihrs",
        name="مركز القاهرة لدراسات حقوق الإنسان",
        url="https://cihrs.org",
        feed_url="https://cihrs.org/feed/",
        source_type="human_rights",
        ownership_type="civil_society",
        language="mixed",
    ),
    SourceInput(
        slug="sinai-foundation",
        name="مؤسسة سيناء لحقوق الإنسان",
        url="https://sinaifhr.org",
        source_type="human_rights",
        ownership_type="civil_society",
    ),
    SourceInput(
        slug="cpj-egypt",
        name="لجنة حماية الصحفيين - مصر",
        url="https://cpj.org/mideast/egypt/",
        source_type="human_rights",
        ownership_type="international_ngo",
        language="en",
    ),
    SourceInput(
        slug="rsf-egypt",
        name="مراسلون بلا حدود - مصر",
        url="https://rsf.org/en/country/egypt",
        source_type="human_rights",
        ownership_type="international_ngo",
        language="en",
    ),
    SourceInput(
        slug="ahram-gate",
        name="بوابة الأهرام",
        url="https://gate.ahram.org.eg",
        source_type="news",
        ownership_type="state_media",
    ),
    SourceInput(
        slug="shorouk-news",
        name="الشروق",
        url="https://www.shorouknews.com",
        source_type="news",
        ownership_type="private_media",
    ),
    SourceInput(
        slug="almasryalyoum",
        name="المصري اليوم",
        url="https://www.almasryalyoum.com",
        feed_url="https://www.almasryalyoum.com/rss/rssfeeds",
        source_type="news",
        ownership_type="private_media",
    ),
    SourceInput(
        slug="masrawy",
        name="مصراوي",
        url="https://www.masrawy.com",
        source_type="news",
        ownership_type="private_media",
    ),
    SourceInput(
        slug="mada-masr",
        name="مدى مصر",
        url="https://www.madamasr.com",
        source_type="investigative",
        ownership_type="independent_media",
        language="mixed",
    ),
    SourceInput(
        slug="manassa",
        name="المنصة",
        url="https://manassa.news",
        source_type="investigative",
        ownership_type="independent_media",
    ),
    SourceInput(
        slug="cairo24",
        name="القاهرة 24",
        url="https://www.cairo24.com",
        source_type="news",
        ownership_type="private_media",
    ),
    SourceInput(
        slug="youm7",
        name="اليوم السابع",
        url="https://www.youm7.com",
        source_type="news",
        ownership_type="private_media",
    ),
    SourceInput(
        slug="akhbar-elyom",
        name="أخبار اليوم",
        url="https://akhbarelyom.com",
        source_type="news",
        ownership_type="state_media",
    ),
]


TOPICS = [
    "التشريعات والقرارات",
    "القضاء والمحاكمات",
    "حرية التعبير والصحافة",
    "الحبس الاحتياطي",
    "الاختفاء القسري",
    "أوضاع السجون",
    "التعذيب وسوء المعاملة",
    "حقوق اللاجئين والمهاجرين",
    "الحقوق العمالية",
    "الحقوق الرقمية",
    "حرية الدين والمعتقد",
    "حقوق المرأة",
    "حقوق الطفل",
    "الاقتصاد والعدالة الاجتماعية",
    "الانتخابات والأحزاب",
    "الصحة والتعليم",
    "السكن والأراضي",
    "سيناء والحدود",
]
