import type { ClaimRecord, EntityRecord, EventRecord, SearchResult, SourceRecord } from "./types.js";

type Story = Record<string, unknown>;
const e = (value: unknown): string => String(value ?? "").replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#39;" })[character]!);
const date = (value: string | null | undefined): string => value ? new Intl.DateTimeFormat("ar-EG", { dateStyle: "medium" }).format(new Date(value)) : "غير محدد";

export const APP_CSS = `:root{color-scheme:dark;font-family:"IBM Plex Sans Arabic","Noto Sans Arabic",system-ui,sans-serif}*{border-radius:0!important}a{text-underline-offset:4px}a:hover{text-decoration:underline}.label{font:700 .72rem ui-monospace,monospace;letter-spacing:.12em;color:#57e389}.metric{font:900 2rem ui-monospace,monospace}.field{background:#080a0b;border:1px solid #596166;padding:.85rem 1rem;outline:none}.field:focus{border-color:#57e389}.action{display:inline-block;background:#57e389;color:#071009;font-weight:900;padding:.9rem 1.2rem;border:1px solid #57e389}.action:hover{background:#eef0e8;text-decoration:none}.section-head{display:flex;justify-content:space-between;align-items:end;gap:1rem;padding-bottom:.75rem;border-bottom:2px solid #eef0e8}.section-head h2{font-size:1.5rem;font-weight:900}.section-head span{font:700 .72rem ui-monospace,monospace;color:#9ca3a8}.source-chip,.export-link{display:inline-block;border:1px solid #596166;padding:.35rem .55rem;font-size:.75rem;font-weight:700}.export-link:hover,.source-chip:hover{border-color:#57e389;text-decoration:none}.result-excerpt{display:-webkit-box;-webkit-box-orient:vertical;-webkit-line-clamp:3;overflow:hidden;line-height:1.75;max-height:5.25em}.empty{border:1px dashed #596166;padding:2rem;color:#9ca3a8}.citation-box{display:grid;grid-template-columns:repeat(3,1fr);border:2px solid #eef0e8}.citation-box div{padding:1rem;border-left:1px solid #596166}.citation-box div:last-child{border-left:0}.citation-box span{display:block;font-size:.7rem;color:#9ca3a8}.citation-box strong{display:block;margin-top:.35rem}.document-text{white-space:pre-line;font-size:1.12rem;line-height:2;color:#d4d8d1}.data-table{width:100%;min-width:760px;border-collapse:collapse}.data-table th,.data-table td{text-align:right;border-bottom:1px solid #42484c;padding:.9rem}.data-table th{font:700 .72rem ui-monospace,monospace;color:#9ca3a8}.status{font:700 .68rem ui-monospace,monospace;border:1px solid #596166;padding:.25rem}.status-healthy,.status-success{color:#57e389;border-color:#57e389}.status-failed{color:#ff6b6b;border-color:#ff6b6b}.prose-block{margin-top:2.5rem;font-size:1.1rem;line-height:2;color:#d4d8d1}.prose-block h2{font-size:1.7rem;font-weight:900;color:#eef0e8;margin:2.5rem 0 .6rem}.prose-block ol{list-style:decimal;padding-right:1.5rem}@media(max-width:640px){.citation-box{grid-template-columns:1fr}.citation-box div{border-left:0;border-bottom:1px solid #596166}.citation-box div:last-child{border-bottom:0}}`;

export const UTILITY_CSS = `*{box-sizing:border-box}html{background:#0a0c0d}body{margin:0;background:#0a0c0d;color:#eef0e8}a{color:inherit}.min-h-screen{min-height:100vh}.mx-auto{margin-inline:auto}.max-w-2xl{max-width:42rem}.max-w-3xl{max-width:48rem}.max-w-4xl{max-width:56rem}.max-w-7xl{max-width:80rem}.flex{display:flex}.grid{display:grid}.flex-col{flex-direction:column}.flex-wrap{flex-wrap:wrap}.grow{flex-grow:1}.grid-cols-3{grid-template-columns:repeat(3,minmax(0,1fr))}.items-center{align-items:center}.items-end{align-items:flex-end}.justify-between{justify-content:space-between}.gap-2{gap:.5rem}.gap-3{gap:.75rem}.gap-4{gap:1rem}.gap-5{gap:1.25rem}.gap-10{gap:2.5rem}.overflow-auto{overflow:auto}.p-3{padding:.75rem}.p-4{padding:1rem}.px-4{padding-inline:1rem}.py-3{padding-block:.75rem}.py-4{padding-block:1rem}.py-5{padding-block:1.25rem}.py-6{padding-block:1.5rem}.py-8{padding-block:2rem}.py-14{padding-block:3.5rem}.pt-14{padding-top:3.5rem}.pb-8{padding-bottom:2rem}.mt-3{margin-top:.75rem}.mt-4{margin-top:1rem}.mt-6{margin-top:1.5rem}.mt-8{margin-top:2rem}.mt-10{margin-top:2.5rem}.mt-12{margin-top:3rem}.mb-2{margin-bottom:.5rem}.border-2{border:2px solid}.border-b{border-bottom:1px solid}.border-b-2{border-bottom:2px solid}.border-t{border-top:1px solid}[class~="border-[#42484c]"]{border-color:#42484c}[class~="border-[#eef0e8]"]{border-color:#eef0e8}.divide-y>*+*{border-top:1px solid #42484c}[class~="bg-[#0a0c0d]"]{background:#0a0c0d}[class~="bg-[#111416]"]{background:#111416}[class~="text-[#57e389]"]{color:#57e389}[class~="text-[#6ea8fe]"]{color:#6ea8fe}[class~="text-[#9ca3a8]"]{color:#9ca3a8}[class~="text-[#b7bec2]"]{color:#b7bec2}[class~="text-[#eef0e8]"]{color:#eef0e8}.text-center{text-align:center}.text-xs{font-size:.75rem}.text-sm{font-size:.875rem}.text-lg{font-size:1.125rem}.text-xl{font-size:1.25rem}.text-2xl{font-size:1.5rem}.text-4xl{font-size:2.25rem}.text-5xl{font-size:3rem}.font-bold{font-weight:700}.font-black{font-weight:900}[class~="leading-[1.05]"]{line-height:1.05}@media(min-width:768px){[class~="md:flex-row"]{flex-direction:row}[class~="md:text-6xl"]{font-size:3.75rem}[class~="md:text-7xl"]{font-size:4.5rem}}@media(min-width:1024px){[class~="lg:grid-cols-3"]{grid-template-columns:repeat(3,minmax(0,1fr))}[class~="lg:grid-cols-[1.4fr_.6fr]"]{grid-template-columns:1.4fr .6fr}}@media(max-width:767px){header nav>div{width:100%;justify-content:space-between;gap:.5rem;font-size:.78rem}.text-5xl{font-size:2.65rem}.grid-cols-3 .metric{font-size:1.75rem}}`;

export function layout(content: string, title = "مرصد مصر البحثي"): string {
  return `<!doctype html><html lang="ar" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="description" content="بنية بحثية مفتوحة وموثقة المصدر للشأن المصري"><meta name="htmx-config" content='{"includeIndicatorStyles":false}'><title>${e(title)}</title><link rel="icon" href="/static/brand.svg" type="image/svg+xml"><script src="https://unpkg.com/htmx.org@2.0.4/dist/htmx.min.js" integrity="sha384-HGfztofotfshcF7+8n44JQL2oJmowVChPTg48S+jvZoztPfvwD79OC/LTtG6dMp+" crossorigin="anonymous"></script><link rel="stylesheet" href="/static/app.css"></head><body class="bg-[#0a0c0d] text-[#eef0e8] min-h-screen"><header class="border-b-2 border-[#eef0e8]"><nav class="max-w-7xl mx-auto px-4 py-4 flex flex-wrap items-center justify-between gap-4"><a href="/" class="font-black text-xl">مرصد مصر البحثي <span class="text-[#57e389]">/ ERX</span></a><div class="flex gap-5 text-sm font-bold"><a href="/explore">البحث</a><a href="/knowledge">المعرفة</a><a href="/sources">المصادر</a><a href="/methodology">المنهجية</a><a href="/docs" class="text-[#6ea8fe]">التوثيق</a></div></nav></header><main>${content}</main><footer class="max-w-7xl mx-auto px-4 py-8 mt-12 border-t border-[#42484c] text-xs text-[#9ca3a8] flex justify-between"><span>بنية معرفة مفتوحة — لا تمنح المصادر درجة حقيقة آلية.</span><a href="/healthz">حالة الخدمة</a></footer></body></html>`;
}

export function homeView(sources: SourceRecord[], stories: Story[]): string {
  const documents = sources.reduce((sum, source) => sum + source.documentCount, 0);
  const storyHtml = stories.length ? `<section class="max-w-7xl mx-auto px-4 py-8"><div class="section-head"><h2>قصص تحت المتابعة</h2><span>تجميع آلي — راجع المصادر</span></div>${stories.map((story) => `<article class="py-5 border-b border-[#42484c]"><h3 class="font-black text-xl">${e(story["title"])}</h3><p class="text-sm text-[#9ca3a8]">${e(story["documentCount"])} وثائق من ${e(story["sourceCount"])} مصادر</p></article>`).join("")}</section>` : "";
  return layout(`<section class="max-w-7xl mx-auto px-4 pt-14 pb-8 grid lg:grid-cols-[1.4fr_.6fr] gap-10 items-end"><div><p class="label">EGYPT RESEARCH COMMONS / TYPESCRIPT</p><h1 class="text-5xl md:text-7xl font-black leading-[1.05] mt-4">ابحث في الشأن المصري.<br><span class="text-[#57e389]">واعرف مصدر كل معلومة.</span></h1><p class="max-w-2xl mt-6 text-[#b7bec2] text-lg">أخبار، وثائق رسمية، قانون، حقوق إنسان، إحصاءات وأبحاث — في فهرس واحد قابل للاستشهاد والمقارنة.</p></div><dl class="grid grid-cols-3 border-2 border-[#eef0e8] text-center"><div class="p-4"><dt class="metric">${documents} وثيقة</dt><dd>في الأرشيف</dd></div><div class="p-4"><dt class="metric">${sources.length} مصدر</dt><dd>في الكتالوج</dd></div><div class="p-4"><dt class="metric">${sources.filter((source) => source.healthStatus === "healthy").length} نشط</dt><dd>آخر جمع</dd></div></dl></section><section class="max-w-7xl mx-auto px-4 py-8"><form class="border-2 border-[#eef0e8] bg-[#111416] p-3 flex flex-col md:flex-row gap-3" hx-get="/search" hx-target="#results"><input name="q" required class="field grow text-lg" placeholder="مثال: قانون العمل، التضخم، حرية الصحافة..."><select name="source_type" class="field"><option value="">كل المصادر</option><option value="official">رسمي</option><option value="legal">قانوني</option><option value="news">إخباري</option><option value="human_rights">حقوقي</option><option value="academic">أكاديمي</option><option value="statistics">إحصائي</option></select><select name="mode" class="field"><option value="hybrid">نصي + دلالي</option><option value="lexical">نصي دقيق</option></select><input name="date_from" type="date" class="field"><input name="date_to" type="date" class="field"><button class="action">ابدأ البحث ←</button></form><div id="results" class="mt-8"></div></section>${storyHtml}`);
}

export function resultsView(query: string, results: SearchResult[], mode: string): string {
  if (!results.length) return `<div class="empty">لا توجد نتائج لعبارة «${e(query)}».</div>`;
  return `<div class="section-head"><h2>${results.length} نتيجة</h2><span>${e(mode)}</span></div><div class="divide-y divide-[#42484c]">${results.map((result) => `<article class="py-6"><div class="flex gap-2 mb-2"><span class="source-chip">${e(result.sourceName)}</span><span class="source-chip">${e(result.sourceType)}</span></div><h3 class="font-black text-2xl"><a href="/documents/${result.documentId}">${e(result.title)}</a></h3><p class="result-excerpt text-[#b7bec2] mt-3">${e(result.excerpt)}</p><p class="text-xs text-[#9ca3a8] mt-3">${date(result.publishedAt)} · <a href="${e(result.canonicalUrl)}" rel="noreferrer">المصدر الأصلي ↗</a></p></article>`).join("")}</div>`;
}

export function documentView(document: SearchResult, entities: EntityRecord[], claims: ClaimRecord[], events: EventRecord[]): string {
  return layout(`<article class="max-w-4xl mx-auto px-4 py-14"><p class="label">وثيقة #${document.documentId}</p><h1 class="text-4xl md:text-6xl font-black mt-4">${e(document.title)}</h1><div class="citation-box mt-8"><div><span>المصدر</span><strong>${e(document.sourceName)}</strong></div><div><span>تاريخ النشر</span><strong>${date(document.publishedAt)}</strong></div><div><span>الرابط</span><strong><a href="${e(document.canonicalUrl)}">الأصل ↗</a></strong></div></div><p class="document-text mt-10">${e(document.content)}</p><section class="mt-12"><div class="section-head"><h2>الكيانات المرتبطة</h2><span>${entities.length}</span></div><div class="flex flex-wrap gap-2 mt-4">${entities.map((entity) => `<span class="source-chip">${e(entity.canonicalName)}</span>`).join("") || "لا توجد"}</div></section><section class="mt-10"><div class="section-head"><h2>الادعاءات المنسوبة</h2><span>${claims.length}</span></div>${claims.map((claim) => `<p class="py-4 border-b border-[#42484c]">${e(claim.claimText)}</p>`).join("") || "<p class='empty mt-4'>لا توجد</p>"}</section><section class="mt-10"><div class="section-head"><h2>الأحداث الموثقة</h2><span>${events.length}</span></div>${events.map((event) => `<p class="py-4">${e(event.title)} — ${date(event.occurredAt)}</p>`).join("")}</section></article>`, document.title);
}

export function sourcesView(sources: SourceRecord[], runs: Record<string, unknown>[]): string {
  return layout(`<section class="max-w-7xl mx-auto px-4 py-14"><div class="section-head"><h1>المصادر</h1><span>${sources.length} مصدر</span></div><div class="overflow-auto"><table class="data-table"><thead><tr><th>المصدر</th><th>النوع</th><th>الملكية</th><th>الجمع</th><th>الحالة</th><th>الوثائق</th></tr></thead><tbody>${sources.map((source) => `<tr><td><a href="${e(source.url)}">${e(source.name)}</a></td><td>${e(source.sourceType)}</td><td>${e(source.ownershipType)}</td><td>${e(source.collectionMethod)}</td><td><span class="status status-${e(source.healthStatus)}">${e(source.healthStatus)}</span></td><td>${source.documentCount}</td></tr>`).join("")}</tbody></table></div><p class="mt-8 text-[#9ca3a8]">${runs.length} عملية جمع مسجلة.</p></section>`, "المصادر — مرصد مصر البحثي");
}

export function knowledgeView(entities: EntityRecord[], events: EventRecord[], claims: ClaimRecord[], saved: Record<string, unknown>[]): string {
  return layout(`<section class="max-w-7xl mx-auto px-4 py-14"><p class="label">KNOWLEDGE GRAPH</p><h1 class="text-5xl font-black mt-4">خريطة المعرفة</h1><div class="grid lg:grid-cols-3 gap-10 mt-12"><section><div class="section-head"><h2>الكيانات</h2><span>${entities.length}</span></div>${entities.slice(0, 30).map((item) => `<p class="py-3 border-b border-[#42484c]">${e(item.canonicalName)} <small>${item.documentCount}</small></p>`).join("")}</section><section><div class="section-head"><h2>الأحداث الموثقة</h2><span>${events.length}</span></div>${events.slice(0, 30).map((item) => `<p class="py-3 border-b border-[#42484c]">${e(item.title)}</p>`).join("")}</section><section><div class="section-head"><h2>الادعاءات</h2><span>${claims.length}</span></div>${claims.slice(0, 30).map((item) => `<p class="py-3 border-b border-[#42484c]">${e(item.claimText)}</p>`).join("")}<p class="mt-8 text-[#9ca3a8]">${saved.length} أبحاث محفوظة</p></section></div></section>`);
}

export function methodologyView(): string { return layout(`<section class="max-w-3xl mx-auto px-4 py-14"><p class="label">METHODOLOGY</p><h1 class="text-5xl font-black mt-4">المنهجية</h1><div class="prose-block"><h2>المبدأ</h2><p>كل نتيجة تعود إلى وثيقة أصلية ورابط وتاريخ. نوع المصدر وملكيته سياق بحثي، وليس درجة حقيقة.</p><h2>ترتيب الأدلة</h2><ol><li>الوثائق الأولية والنصوص القانونية والإحصاءات الرسمية.</li><li>التغطية المستقلة والتحقيقات المتقاطعة.</li><li>البيانات الحقوقية والمنهجيات المنشورة.</li></ol><h2>الحدود</h2><p>قد تتعطل قنوات الجمع أو تتغير بنية المواقع. تكرار الادعاء لا يجعله حقيقة تلقائيًا.</p></div></section>`); }
